### ISSUE TITLE
Navigation Cleaning and Intuition

### ISSUE THREAD

**Issue by Mehul20** [avirathtib/crypto-news#10]
Make sure that Navigation works smoothly.

**Comment by Mehul20** [comment]
1) Remove Log In /Sign up from the Table page. 
2) Add, Hello "#name" 👋 instead
3) Implement log out
4) Reduce Width
5) Increase font weight 
6) Change Font-Family

**Comment by Mehul20** [comment]
@Surabhi7602 can you please display the normal navbar normally irrespective of login status on the tablewithoutloginpage

**Comment by Surabhi7602** [comment]
done
